2022-04-15 16:06:13,854 ERROR: Exception on /static/style.css [GET]
Traceback (most recent call last):
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 515, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "D:\data\flaskroute\lib\site-packages\flask\scaffold.py", line 328, in send_static_file
    return send_from_directory(
  File "D:\data\flaskroute\lib\site-packages\flask\helpers.py", line 675, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore
  File "D:\data\flaskroute\lib\site-packages\werkzeug\utils.py", line 584, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1384, in handle_user_exception
    return self.handle_http_exception(e)
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "E:\python_work\python_workspaces\flaskroute\app.py", line 61, in page_not_found
    return render_template('404.html'), 404
  File "D:\data\flaskroute\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\data\flaskroute\lib\site-packages\jinja2\environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\data\flaskroute\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\data\flaskroute\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\data\flaskroute\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\data\flaskroute\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "D:\data\flaskroute\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
2022-04-15 16:06:13,854 ERROR: Exception on /static/style.css [GET]
Traceback (most recent call last):
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 515, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "D:\data\flaskroute\lib\site-packages\flask\scaffold.py", line 328, in send_static_file
    return send_from_directory(
  File "D:\data\flaskroute\lib\site-packages\flask\helpers.py", line 675, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore
  File "D:\data\flaskroute\lib\site-packages\werkzeug\utils.py", line 584, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1384, in handle_user_exception
    return self.handle_http_exception(e)
  File "D:\data\flaskroute\lib\site-packages\flask\app.py", line 1324, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "E:\python_work\python_workspaces\flaskroute\app.py", line 61, in page_not_found
    return render_template('404.html'), 404
  File "D:\data\flaskroute\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\data\flaskroute\lib\site-packages\jinja2\environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\data\flaskroute\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\data\flaskroute\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\data\flaskroute\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\data\flaskroute\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "D:\data\flaskroute\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
